import UserCheckAuth from "@/hooks/UserContext";
import type { Metadata } from "next";
import { cookies } from "next/headers";

export const metadata: Metadata = {
  title: "Varon AI",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const token = cookieStore.get("token_id_user")?.value || "";

  return (
    <div>
      <UserCheckAuth token={token}>{children}</UserCheckAuth>
    </div>
  );
}
