import UserCheckAuth from "@/hooks/userCheck";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Varon AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <UserCheckAuth>{children}</UserCheckAuth>
      </body>
    </html>
  );
}
