import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "./theme/ThemeToogle";

export const metadata: Metadata = {
  title: "Varon AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
