import PDFDocument from "pdfkit";
import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
} from "docx";
import PptxGenJS from "pptxgenjs";

async function generatePDF(title, content) {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument();
      const buffers = [];

      doc.on("data", (chunk) => buffers.push(chunk));
      doc.on("end", () => {
        const pdfData = Buffer.concat(buffers);
        resolve(pdfData);
      });

      doc.fontSize(24).font("Helvetica-Bold").text(title, { align: "center" });
      doc.moveDown();

      doc.fontSize(12).font("Helvetica").text(content, {
        align: "left",
        paragraphGap: 10,
        indent: 20,
      });

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
}

async function generateDOCX(title, content) {
  const paragraphs = content.split("\n").map((line) => {
    if (line.trim().length === 0) return new Paragraph(""); 
    return new Paragraph({
      children: [new TextRun({ text: line, size: 24 })],
      spacing: { after: 200 },
    });
  });

  const doc = new Document({
    sections: [
      {
        properties: {},
        children: [
          new Paragraph({
            text: title,
            heading: HeadingLevel.TITLE,
            alignment: AlignmentType.CENTER,
            spacing: { after: 400 },
          }),
          ...paragraphs,
        ],
      },
    ],
  });

  return await Packer.toBuffer(doc);
}

async function generatePPTX(title, content) {
  const pptx = new PptxGenJS();

  let slide = pptx.addSlide();
  slide.addText(title, {
    x: 1,
    y: 1,
    w: "80%",
    h: 1,
    fontSize: 36,
    align: "center",
    bold: true,
  });
  slide.addText("Generated by ScriptForge via Varon AI", {
    x: 1,
    y: 3,
    w: "80%",
    h: 1,
    fontSize: 18,
    align: "center",
    color: "808080",
  });

  const contentSlide = pptx.addSlide();
  contentSlide.addText("Overview", {
    x: 0.5,
    y: 0.5,
    w: "90%",
    h: 0.5,
    fontSize: 24,
    bold: true,
    color: "003366",
  });

  contentSlide.addText(content, {
    x: 0.5,
    y: 1.2,
    w: "90%",
    h: 4,
    fontSize: 14,
    color: "363636",
    valign: "top",
  });

  return await pptx.write("nodebuffer");
}
export async function generateDocument({ format, title, content }) {
  try {
    let buffer;
    switch (format.toLowerCase()) {
      case "pdf":
        buffer = await generatePDF(title, content);
        break;
      case "docx":
        buffer = await generateDOCX(title, content);
        break;
      case "pptx":
        buffer = await generatePPTX(title, content);
        break;
      default:
        throw new Error(
          `Unsupported format: ${format}. Please choose pdf, docx, or pptx.`
        );
    }
    return { success: true, buffer };
  } catch (error) {
    console.error("ScriptForge Logic Error:", error);
    throw new Error(`Failed to generate document: ${error.message}`);
  }
}
